// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJ0Uw8hM4HLxGNqycg3fpZOLcW7gmO-I',
    appId: '1:269364737307:web:4f56a1154122b6f9000fbe',
    messagingSenderId: '269364737307',
    projectId: 'betterspent-2568',
    authDomain: 'betterspent-2568.firebaseapp.com',
    storageBucket: 'betterspent-2568.firebasestorage.app',
    measurementId: 'G-X8FRHY1FD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVy0SNInmidYgr7Ke7uSDTQp0ApuTmSU0',
    appId: '1:269364737307:android:26faa8e74621f483000fbe',
    messagingSenderId: '269364737307',
    projectId: 'betterspent-2568',
    storageBucket: 'betterspent-2568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb5ojqkqjqmF4R_rigo5WPnksYsugt_K4',
    appId: '1:269364737307:ios:fbf14c28a1b8389f000fbe',
    messagingSenderId: '269364737307',
    projectId: 'betterspent-2568',
    storageBucket: 'betterspent-2568.firebasestorage.app',
    iosBundleId: 'com.example.betterSpent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb5ojqkqjqmF4R_rigo5WPnksYsugt_K4',
    appId: '1:269364737307:ios:fbf14c28a1b8389f000fbe',
    messagingSenderId: '269364737307',
    projectId: 'betterspent-2568',
    storageBucket: 'betterspent-2568.firebasestorage.app',
    iosBundleId: 'com.example.betterSpent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVJ0Uw8hM4HLxGNqycg3fpZOLcW7gmO-I',
    appId: '1:269364737307:web:e83cfb1c3500c56d000fbe',
    messagingSenderId: '269364737307',
    projectId: 'betterspent-2568',
    authDomain: 'betterspent-2568.firebaseapp.com',
    storageBucket: 'betterspent-2568.firebasestorage.app',
    measurementId: 'G-7X40836Q71',
  );
}
