import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // ✅ auto-generated by flutterfire configure
import 'core/constants/app_colors.dart';
import 'core/router/app_router.dart';
import 'core/services/app_launch_service.dart';
import 'presentation/providers/app_provider.dart';

void main() async {
  // ✅ Required before using any async plugin
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  var envLoaded = false;
  try {
    await dotenv.load(fileName: '.env');
    envLoaded = true;
  } catch (e, st) {
    debugPrint('Could not load .env: $e');
    debugPrintStack(stackTrace: st);
  }
  if (!envLoaded) {
    try {
      await dotenv.load(fileName: 'assets/.env');
      envLoaded = true;
    } catch (e, st) {
      debugPrint('Could not load assets/.env: $e');
      debugPrintStack(stackTrace: st);
    }
  }

  // ✅ Initialize Firebase with generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await _activateAppCheck();
  try {
    await AppLaunchService.initialize();
  } catch (e, st) {
    debugPrint('AppLaunchService init failed: $e');
    debugPrintStack(stackTrace: st);
  }

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppProvider()..initialize(),
      child: const BetterSpentApp(),
    ),
  );
}

Future<void> _activateAppCheck() async {
  const webRecaptchaSiteKey = String.fromEnvironment('WEB_RECAPTCHA_SITE_KEY');
  try {
    await FirebaseAppCheck.instance.activate(
      webProvider: webRecaptchaSiteKey.isNotEmpty
          ? ReCaptchaV3Provider(webRecaptchaSiteKey)
          : ReCaptchaV3Provider('missing-site-key'),
      androidProvider: AndroidProvider.playIntegrity,
      appleProvider: AppleProvider.appAttest,
    );
  } catch (e, st) {
    debugPrint('Firebase App Check activate failed: $e');
    debugPrintStack(stackTrace: st);
  }
}

class BetterSpentApp extends StatelessWidget {
  const BetterSpentApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: AppRouter.appRouter,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: AppColors.background,
        canvasColor: AppColors.background,
      ),
    );
  }
}
